const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "..", "dist");
const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>JFrog Supply-Chain Demo</title>
  </head>
  <body>
    <main>
      <h1>JFrog Supply-Chain Demo</h1>
      <p>Frontend build artifact generated by npm.</p>
    </main>
  </body>
</html>
`;

fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(path.join(distDir, "index.html"), html);

if (process.argv.includes("--check")) {
  const built = fs.existsSync(path.join(distDir, "index.html"));
  if (!built) {
    throw new Error("Frontend build artifact was not created.");
  }
}

console.log("Frontend build complete: dist/index.html");
